### PR TITLE
Fix for Tutorial Island Portal

### PR DESCRIPTION
**Pull request by TacoShower**
The tutorial island portal is not registered, so nearest is returning null as destinations is empty. This fix simply checks if nearest is null (no registered portals) and if so it registers the portal and recalculates nearest. This prevents it from crashing when interacting with the tutorial island portal. A better fix might be looking at how the tutorial island is spawned and why it isn't being registered on create but I was unable to find that myself.

### CODE REVIEW

**Comment by TacoShower** [comment]
this would fix this commit fixes issue #2

**Comment by miicck** [comment]
Hey @TacoShower, thanks for the fix. Assuming it works, I'll happily pull it in for the next update. Is there a reason you marked it as closed?

**Comment by TacoShower** [comment]
Updated pull request [here](https://github.com/miicck/dont-get-lost/pull/15) Sorry I’m new to making pull requests so I accidentally made two and closed this one

**Comment by miicck** [comment]
Ah, hadn't spotted the new one, thanks!

**Pull request closed without merging**
